In [1]:
import numpy as np

In [3]:
a1=np.arange(5,31,5)
print(a1)

[ 5 10 15 20 25 30]


In [5]:
a2=np.zeros((4,5))
print(a2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
a3=np.identity(5)
print(a3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
a4=np.linspace(0,1,8)
print(a4)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [8]:
a5=np.random.random((3,3))
print(a5)

[[0.42942928 0.39323547 0.75126138]
 [0.26421679 0.86189332 0.52979779]
 [0.81729945 0.42729491 0.0196116 ]]


In [ ]:
a6=np.arange(1,13).reshape(3,4)
print(a6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(a6.shape)
print(a6.ndim)
print(a6.size)
print(a6.dtype)
print(a6.itemsize)

(3, 4)
2
12
int64
8


In [14]:
a6=a6.astype(float)
print(a6)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [15]:
a6=a6*5
print(a6)

[[ 5. 10. 15. 20.]
 [25. 30. 35. 40.]
 [45. 50. 55. 60.]]


In [16]:
print(a6>7)

[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [20]:
arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
print(arr[3])

[16 17 18 19 20]


In [21]:
print(arr[:,1])

[ 2  7 12 17 22]


In [26]:
print(arr[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [30]:
print(arr[0::4,0::4])

[[ 1  5]
 [21 25]]


In [31]:
print(arr[::2])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [34]:
arr = np.random.randint(1,101,(5,5))
print(arr)

[[31 46 80 53 56]
 [12 67 75  7 20]
 [ 1 86 79 34  1]
 [50 52 39 99  9]
 [96 27 69 37 44]]


In [42]:
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr,axis=1))
print(np.mean(arr,axis=0))
print(np.std(arr))

99
1
[266 181 201 249 273]
[38.  55.6 68.4 46.  26. ]
28.834701316295963


In [46]:
A = np.arange(1,10).reshape(3,3)

B = np.arange(10,19).reshape(3,3)
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [44]:
print(A+B)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [45]:
print(A*B)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [47]:
print(np.dot(A,B))

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [49]:
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [51]:
print(np.ravel(A))

[1 2 3 4 5 6 7 8 9]


Numpy are faster than python lists because they use contigous memory allocation

In numpy size gives us total no of elements whereas shape gives us sutrucure of that matrix in form of (row,column)

Ndim returns us no of dimensions in an array

Scalar operation is applied on a matrix and a single element whereas vector operations are done or applied between two matrices

we would use reshape when we need a matrix in 2d or 3d as it gives us oppurtunity to change matrix in any dimesional form

transpose reverses the matrix whereas ravel flatten the matrix into 1d matrix

axis lets us use operations on rows or columns like axis=0 is for columuns whereas axis 1 is for rows

In [53]:
a7=np.arange(1,6)

table=a7[:,np.newaxis]*a7

print(table)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
