In [2]:
#np.array
import numpy as np

a=np.array([1,2,3])
print(a)


[1 2 3]


In [3]:
#2d and #3d
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print(c)


[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
#np.arange

d=np.arange(1,11,2)
print(d)

[1 3 5 7 9]


In [9]:
#with resphape

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#np.ones and np.zeros => This gives us a numpy 2d array of the ones and zeros with the size provided
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
#np.random

np.random.random((3,4))

array([[0.95686895, 0.05127494, 0.98528843, 0.8882887 ],
       [0.3324551 , 0.06707038, 0.36110235, 0.37905588],
       [0.97223404, 0.78839674, 0.27020907, 0.29159724]])

In [ ]:
#np.linspace(lower_range,higher_range,no of elements)=>gives linear seprable points

np.linspace(-10,10,10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
#np.identity => to create identity matrix
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [16]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [18]:
#ndim => no of dimensions

a1.ndim
a2.ndim
a3.ndim

3

In [19]:
#shape => tell us no of rows and colums in a matrix

print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [21]:
#size => tells no of elements

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
#item size => no of bytes an item is storing in an array

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [26]:
#dtype => tell us the data type of elemnts in our numpy array

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Datatype

In [32]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [9]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#scalar operation

#airthmetic
a1*2

#relational
a2>16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vector operations(for same shape)

#airthmetic

a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Functions

In [14]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[61., 78., 79.],
       [75., 11., 31.],
       [ 1., 92., 31.]])

In [ ]:
#max/min/sum/prod 
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.max(a1,axis=1) #0->column 1->row works with all functions

array([79., 75., 92.])

In [22]:
#mean/median/std/var
np.mean(a1)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis=1)

array([  68.22222222,  714.66666667, 1433.55555556])

In [23]:
#trignometric functions
np.sin(a1)

array([[-0.96611777,  0.51397846, -0.44411267],
       [-0.38778164, -0.99999021, -0.40403765],
       [ 0.84147098, -0.77946607, -0.40403765]])

In [24]:
# dot product

a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a1,a2)

array([[ 944., 1162., 1380., 1598.],
       [ 292.,  409.,  526.,  643.],
       [ 616.,  740.,  864.,  988.]])

In [26]:
#log and exponents
np.log(a1)
np.exp(a1)


array([[3.10429794e+26, 7.49841700e+33, 2.03828107e+34],
       [3.73324200e+32, 5.98741417e+04, 2.90488497e+13],
       [2.71828183e+00, 9.01762841e+39, 2.90488497e+13]])

In [29]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[54., 84., 54.],
       [59., 50., 43.]])

# Indexing and Slicing

In [30]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [31]:
a1[-1]

np.int64(9)

In [34]:
a2[1,2]
a2[2,3]

np.int64(11)

In [36]:
a3[1,0,1]

np.int64(5)

In [37]:
a3[0,1,0]

np.int64(2)

In [38]:
a3[0,0,0]

np.int64(0)

In [39]:
a3[1,1,0]

np.int64(6)

In [41]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [43]:
a2[:,2]

array([ 2,  6, 10])

In [44]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [49]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [50]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [52]:
a2[1,::3]

array([4, 7])

In [57]:
a2[:2:,1::2]

array([[1, 3],
       [5, 7]])

In [61]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [67]:
a3[0,1]

array([3, 4, 5])

In [68]:
a3[1,:,1]

array([10, 13, 16])

In [70]:
a3[2,1::,1::]

array([[22, 23],
       [25, 26]])

In [74]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [78]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [79]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [80]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3): #to iterate on per item in 2d and 3d array
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
# reshape => studied earlier

In [83]:
# Transpose
np.transpose(a2)
#or
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#Ravel => 2d or 3d to 1d array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [86]:
# Horizontal Stacking

a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [88]:
# Vertical Stacking

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [90]:
#Horizontal Splitting

a4
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [92]:
#Verical Slicing
a5
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]