In [1]:
import numpy as np
arr = np.arange(1, 21)

In [2]:
print(arr[:5])
print(arr[-5:])
print(arr[5:15])

[1 2 3 4 5]
[16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15]


In [8]:
arr=np.arange(1,26).reshape(5,5)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5, 5)
2
25
int64


In [11]:
arr=np.arange(10,60,10)
arr=arr.astype(np.float64)
print(arr)

[10. 20. 30. 40. 50.]


In [14]:
arr = np.arange(1, 11)
print(arr[arr%2==0])

[ 2  4  6  8 10]


In [22]:
arr = np.array([10, 25, 3, 48, 17, 90, 6])
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

90
3
28.428571428571427
17.0
28.799092956238063


In [30]:
arr = np.arange(1, 13).reshape(3, 4)
print(np.sum(arr))
print(np.sum(arr,axis=1))
print(np.sum(arr,axis=0))

78
[10 26 42]
[15 18 21 24]


In [36]:
A = np.arange(1, 10).reshape(3, 3)
print(A.T)
print(A.ravel())
print(A*10)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [38]:
arr = np.arange(1, 10).reshape(3, 3)
values = np.array([10, 20, 30])
print(arr+values)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [40]:
arr = np.array([12, 5, 27, 8, 45, 19, 3, 31])
new_arr=arr[arr>20]
print(new_arr)

[27 45 31]


In [42]:
marks = np.array([
    [78, 85, 91],
    [65, 72, 80],
    [90, 88, 95],
    [55, 68, 70]
])
print(np.mean(marks,axis=1))
print(np.mean(marks,axis=0))
print(np.max(marks))
print(np.argmax(np.mean(marks,axis=1)))
print(marks[marks>85])

[84.66666667 72.33333333 91.         64.33333333]
[72.   78.25 84.  ]
95
2
[91 90 88 95]


axis 0 is used for columns it is used for functions like sum,max and more if we want to use these functions only on columns

axis 1 is used for rows

In NumPy, arr.mean(axis=0) gives one value per column because axis=0 points down the rows.

arr.reshpae(3,3) reshapes the array into given dimensions of row and column and it even can be of any dimension whereas ravel flatten the given array into 1d from higher dimnesions

It describes how numpy treats arrays with diffrent shapes during airthmetic operations
The smaller array is "broadcast" across the larger array so that they have compatible shapes