# Numpy tricks

In [3]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([60, 56, 76,  8, 50, 90, 65,  7, 99, 82, 57, 99, 68,  5, 23],
      dtype=int32)

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[78, 60, 53, 68],
       [94, 13, 32, 96],
       [ 8, 21, 82, 71],
       [35, 32,  4, 29],
       [88, 96, 22, 37],
       [ 4, 44, 68, 24]], dtype=int32)

In [8]:
np.sort(a)
np.sort(a)[::-1]

array([99, 99, 90, 82, 76, 68, 65, 60, 57, 56, 50, 23,  8,  7,  5],
      dtype=int32)

In [7]:
np.sort(b) #default is row wise
np.sort(b,axis=0)

array([[ 4, 13,  4, 24],
       [ 8, 21, 22, 29],
       [35, 32, 32, 37],
       [78, 44, 53, 68],
       [88, 60, 68, 71],
       [94, 96, 82, 96]], dtype=int32)

# The numpy.append() appends values along the mentioned axis at the end of array

In [10]:
np.append(a,200)

array([ 60,  56,  76,   8,  50,  90,  65,   7,  99,  82,  57,  99,  68,
         5,  23, 200])

In [12]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[78., 60., 53., 68.,  1.],
       [94., 13., 32., 96.,  1.],
       [ 8., 21., 82., 71.,  1.],
       [35., 32.,  4., 29.,  1.],
       [88., 96., 22., 37.,  1.],
       [ 4., 44., 68., 24.,  1.]])

# numpy.concatenate() fuction concentrate a sequence of arrays along an existing axis

In [13]:
c= np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# with the help of np.unique() method we can get the unique values from an array given as parameter in np.unique() method

In [16]:
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])


In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# with the help of np.expand_dims() method,we can get expanded dimensions of an array

In [18]:
a

array([60, 56, 76,  8, 50, 90, 65,  7, 99, 82, 57, 99, 68,  5, 23],
      dtype=int32)

In [20]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [22]:
np.expand_dims(a,axis=1)

array([[60],
       [56],
       [76],
       [ 8],
       [50],
       [90],
       [65],
       [ 7],
       [99],
       [82],
       [57],
       [99],
       [68],
       [ 5],
       [23]], dtype=int32)

# The numpy.where() fuctions return the indices of element in an input array where the given conditions is satisfied

In [23]:
a

array([60, 56, 76,  8, 50, 90, 65,  7, 99, 82, 57, 99, 68,  5, 23],
      dtype=int32)

In [24]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  5,  6,  8,  9, 10, 11, 12]),)

In [26]:
#replace all values greater than 50 with 0
#np.where(condition,if true,if false)
np.where(a>50,0,a)

array([ 0,  0,  0,  8, 50,  0,  0,  7,  0,  0,  0,  0,  0,  5, 23],
      dtype=int32)

# The numpy.argmax() fuction return indices of max element of the array in a particular axis

In [27]:
a

array([60, 56, 76,  8, 50, 90, 65,  7, 99, 82, 57, 99, 68,  5, 23],
      dtype=int32)

In [28]:
np.argmax(a)

np.int64(8)

In [30]:
b

array([[78, 60, 53, 68],
       [94, 13, 32, 96],
       [ 8, 21, 82, 71],
       [35, 32,  4, 29],
       [88, 96, 22, 37],
       [ 4, 44, 68, 24]], dtype=int32)

In [31]:
np.argmax(b,axis=0)
np.argmax(b,axis=1)

array([0, 3, 2, 0, 1, 2])

# numpy.argmin is same as argmax only diffrence is it gives indices of the minimum element in an array

In [32]:
np.argmin(a)

np.int64(13)

# numpy.cumsum() fuction is used when we want to compute the comulative sum of array element over a given axis

In [33]:
a

array([60, 56, 76,  8, 50, 90, 65,  7, 99, 82, 57, 99, 68,  5, 23],
      dtype=int32)

In [34]:
np.cumsum(a)

array([ 60, 116, 192, 200, 250, 340, 405, 412, 511, 593, 650, 749, 817,
       822, 845])

In [35]:
b

array([[78, 60, 53, 68],
       [94, 13, 32, 96],
       [ 8, 21, 82, 71],
       [35, 32,  4, 29],
       [88, 96, 22, 37],
       [ 4, 44, 68, 24]], dtype=int32)

In [37]:
np.cumsum(b) # for default case if you have not provided any axis it converts 2d to 1d and then perform communicative sum of that array

array([  78,  138,  191,  259,  353,  366,  398,  494,  502,  523,  605,
        676,  711,  743,  747,  776,  864,  960,  982, 1019, 1023, 1067,
       1135, 1159])

In [38]:
np.cumsum(b,axis=0)

array([[ 78,  60,  53,  68],
       [172,  73,  85, 164],
       [180,  94, 167, 235],
       [215, 126, 171, 264],
       [303, 222, 193, 301],
       [307, 266, 261, 325]])

In [39]:
np.cumsum(b,axis=1)

array([[ 78, 138, 191, 259],
       [ 94, 107, 139, 235],
       [  8,  29, 111, 182],
       [ 35,  67,  71, 100],
       [ 88, 184, 206, 243],
       [  4,  48, 116, 140]])

In [40]:
#np.cumprod is same only diffrence it perfrorms commucicative product rather than communicative sum
np.cumprod(a)

array([                  60,                 3360,               255360,
                    2042880,            102144000,           9192960000,
               597542400000,        4182796800000,      414096883200000,
          33955944422400000,  1935488832076800000,  7145953638507683840,
        6309501502074159104, -5345980637048307712,  6169653863855783936])

# Numpy.percentile() fuction is used to compute the nth percentile of the given data(array elements) along the specified axis

In [41]:
a

array([60, 56, 76,  8, 50, 90, 65,  7, 99, 82, 57, 99, 68,  5, 23],
      dtype=int32)

In [46]:
np.percentile(a,70)

np.float64(74.39999999999999)

# Numpy.histogram() function represents the frequency of data distribution in the graphical form

In [47]:
a

array([60, 56, 76,  8, 50, 90, 65,  7, 99, 82, 57, 99, 68,  5, 23],
      dtype=int32)

In [48]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 0, 1, 0, 0, 3, 3, 1, 1, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# numpy.corrcoef returns Pearson product-moment corelation coefficients

In [49]:
salary=np.array([2000,4000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.19773323],
       [0.19773323, 1.        ]])

# numpy.isin() method we can see that one array having values checked in a numpy array having diffrent elements with diffrent sizes

In [50]:
a

array([60, 56, 76,  8, 50, 90, 65,  7, 99, 82, 57, 99, 68,  5, 23],
      dtype=int32)

In [52]:
items=[10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60, 50, 90], dtype=int32)

In [53]:
a

array([60, 56, 76,  8, 50, 90, 65,  7, 99, 82, 57, 99, 68,  5, 23],
      dtype=int32)

In [54]:
np.flip(a)

array([23,  5, 68, 99, 57, 82, 99,  7, 65, 90, 50,  8, 76, 56, 60],
      dtype=int32)

In [55]:
b

array([[78, 60, 53, 68],
       [94, 13, 32, 96],
       [ 8, 21, 82, 71],
       [35, 32,  4, 29],
       [88, 96, 22, 37],
       [ 4, 44, 68, 24]], dtype=int32)

In [ ]:
np.flip(b) #For default case there will be row flipping as well as column flipping

array([[24, 68, 44,  4],
       [37, 22, 96, 88],
       [29,  4, 32, 35],
       [71, 82, 21,  8],
       [96, 32, 13, 94],
       [68, 53, 60, 78]], dtype=int32)

In [58]:
np.flip(b,axis=0)
np.flip(b,axis=1)

array([[68, 53, 60, 78],
       [96, 32, 13, 94],
       [71, 82, 21,  8],
       [29,  4, 32, 35],
       [37, 22, 96, 88],
       [24, 68, 44,  4]], dtype=int32)

# The numpy.put() fuction replaces specific elements of an array with given values of p_array . Array indexed works on flattened arrays

In [61]:
a

array([110, 530,  76,   8,  50,  90,  65,   7,  99,  82,  57,  99,  68,
         5,  23], dtype=int32)

In [ ]:
np.put(a,[0,1],[110,530]) #It makes changes directly to orignal array

# The numpy.delete() fuction returns a new array with the deletion of sub-arrays along the mentioned axis

In [62]:
a

array([110, 530,  76,   8,  50,  90,  65,   7,  99,  82,  57,  99,  68,
         5,  23], dtype=int32)

In [64]:
np.delete(a,[0,2,4])

array([530,   8,  90,  65,   7,  99,  82,  57,  99,  68,   5,  23],
      dtype=int32)

# Set Functions

In [65]:
#np.union1d
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [66]:
np.intersect1d(m,n)

array([3, 4, 5])

In [67]:
np.setdiff1d(m,n)

array([1, 2])

In [68]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [69]:
np.in1d(m,1)

C:\Users\Raman Bhatia\AppData\Local\Temp\ipykernel_11380\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

# numpy.clip() fuction is used to clip(limit) the values in an array

In [70]:
a

array([110, 530,  76,   8,  50,  90,  65,   7,  99,  82,  57,  99,  68,
         5,  23], dtype=int32)

In [71]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 50, 75, 65, 25, 75, 75, 57, 75, 68, 25, 25],
      dtype=int32)